/**
 * DO NOT EDIT. Generated by ontology/gen_code.py from
 * ontology/duap-ontology-v1.json (sha256 68fcb23de2d63a4f2a216df14e048d51...).
 * Edit the ontology and regenerate; CI fails if this file is stale.
 */

export const ONTOLOGY_VERSION = "1.0.0-draft";
export const ONTOLOGY_SHA256 = "68fcb23de2d63a4f2a216df14e048d519fbac744e1dfdecb0f69bd80d4fe4a41";

/** Sensitivity tiers. */
export type SensitivityTier =
  | "t0"
  | "t1"
  | "t2"
  | "t3"
  | "t4";

export const SENSITIVITYTIER_ALL: readonly SensitivityTier[] = [
  "t0",
  "t1",
  "t2",
  "t3",
  "t4",
];

/** Data classes. */
export type DataClass =
  | "identity.direct"
  | "identity.pseudonymous"
  | "identity.government"
  | "contact.email"
  | "contact.phone"
  | "contact.postal"
  | "location.precise"
  | "location.coarse"
  | "location.inferred_home"
  | "location.inferred_work"
  | "location.trajectory"
  | "device.identifier"
  | "device.fingerprint"
  | "device.configuration"
  | "device.network"
  | "behavior.web_browsing"
  | "behavior.app_usage"
  | "behavior.search"
  | "behavior.content_consumption"
  | "behavior.social_graph"
  | "behavior.keystroke_dynamics"
  | "behavior.attention"
  | "transaction.purchase"
  | "transaction.payment_instrument"
  | "financial.account"
  | "financial.creditworthiness"
  | "financial.income"
  | "content.user_generated"
  | "content.communications"
  | "content.media"
  | "biometric.template"
  | "biometric.derived"
  | "health.clinical"
  | "health.wearable"
  | "health.inferred"
  | "protected.race_ethnicity"
  | "protected.religion"
  | "protected.political"
  | "protected.sexual_orientation"
  | "protected.genetic"
  | "protected.immigration"
  | "minor.any"
  | "education.record"
  | "employment.record"
  | "telemetry.enterprise"
  | "telemetry.security"
  | "telemetry.vehicle"
  | "telemetry.iot_home"
  | "telemetry.iot_industrial"
  | "sensor.environmental"
  | "sensor.imaging_public"
  | "industrial.process"
  | "scientific.measurement"
  | "scientific.human_subject"
  | "derived.profile"
  | "derived.segment"
  | "derived.embedding"
  | "derived.aggregate"
  | "derived.dp_aggregate"
  | "derived.synthetic"
  | "derived.model_parameters";

export const DATACLASS_ALL: readonly DataClass[] = [
  "identity.direct",
  "identity.pseudonymous",
  "identity.government",
  "contact.email",
  "contact.phone",
  "contact.postal",
  "location.precise",
  "location.coarse",
  "location.inferred_home",
  "location.inferred_work",
  "location.trajectory",
  "device.identifier",
  "device.fingerprint",
  "device.configuration",
  "device.network",
  "behavior.web_browsing",
  "behavior.app_usage",
  "behavior.search",
  "behavior.content_consumption",
  "behavior.social_graph",
  "behavior.keystroke_dynamics",
  "behavior.attention",
  "transaction.purchase",
  "transaction.payment_instrument",
  "financial.account",
  "financial.creditworthiness",
  "financial.income",
  "content.user_generated",
  "content.communications",
  "content.media",
  "biometric.template",
  "biometric.derived",
  "health.clinical",
  "health.wearable",
  "health.inferred",
  "protected.race_ethnicity",
  "protected.religion",
  "protected.political",
  "protected.sexual_orientation",
  "protected.genetic",
  "protected.immigration",
  "minor.any",
  "education.record",
  "employment.record",
  "telemetry.enterprise",
  "telemetry.security",
  "telemetry.vehicle",
  "telemetry.iot_home",
  "telemetry.iot_industrial",
  "sensor.environmental",
  "sensor.imaging_public",
  "industrial.process",
  "scientific.measurement",
  "scientific.human_subject",
  "derived.profile",
  "derived.segment",
  "derived.embedding",
  "derived.aggregate",
  "derived.dp_aggregate",
  "derived.synthetic",
  "derived.model_parameters",
];

/** Collection methods. */
export type CollectionMethod =
  | "explicit.form"
  | "explicit.upload"
  | "passive.cookie"
  | "passive.pixel"
  | "passive.sdk"
  | "passive.server_log"
  | "passive.fingerprint"
  | "passive.network"
  | "device.sensor"
  | "device.os_api"
  | "observation.camera"
  | "observation.audio"
  | "machine.vehicle_bus"
  | "machine.industrial_bus"
  | "acquisition.third_party"
  | "acquisition.broker"
  | "acquisition.public"
  | "acquisition.scrape"
  | "inference.derived";

export const COLLECTIONMETHOD_ALL: readonly CollectionMethod[] = [
  "explicit.form",
  "explicit.upload",
  "passive.cookie",
  "passive.pixel",
  "passive.sdk",
  "passive.server_log",
  "passive.fingerprint",
  "passive.network",
  "device.sensor",
  "device.os_api",
  "observation.camera",
  "observation.audio",
  "machine.vehicle_bus",
  "machine.industrial_bus",
  "acquisition.third_party",
  "acquisition.broker",
  "acquisition.public",
  "acquisition.scrape",
  "inference.derived",
];

/** Measurement units. */
export type Unit =
  | "record"
  | "byte"
  | "subject_day"
  | "query"
  | "inference"
  | "impression"
  | "token"
  | "comparison"
  | "episode"
  | "retrieval"
  | "gradient_step"
  | "share";

export const UNIT_ALL: readonly Unit[] = [
  "record",
  "byte",
  "subject_day",
  "query",
  "inference",
  "impression",
  "token",
  "comparison",
  "episode",
  "retrieval",
  "gradient_step",
  "share",
];

/** Operations. */
export type Operation =
  | "collect.observe"
  | "collect.receive"
  | "collect.generate"
  | "store.persist"
  | "store.replicate"
  | "store.backup"
  | "access.read"
  | "access.query"
  | "access.index"
  | "access.export_view"
  | "process.transform"
  | "process.aggregate"
  | "process.classify"
  | "process.profile"
  | "process.score"
  | "process.personalize"
  | "process.recommend"
  | "process.predict"
  | "process.match"
  | "process.deidentify"
  | "process.anonymize"
  | "process.dp_release"
  | "transfer.internal"
  | "transfer.affiliate"
  | "transfer.processor"
  | "transfer.controller"
  | "transfer.sale"
  | "transfer.license"
  | "transfer.api_access"
  | "transfer.export_jurisdiction"
  | "transfer.publish"
  | "ai.pretrain"
  | "ai.finetune"
  | "ai.instruction_tune"
  | "ai.preference_data"
  | "ai.rl_environment"
  | "ai.embed"
  | "ai.index_retrieval"
  | "ai.retrieve"
  | "ai.inference_input"
  | "ai.evaluate"
  | "ai.synthesize"
  | "ai.distill"
  | "ai.unlearn"
  | "commercial.advertise"
  | "commercial.measure"
  | "commercial.price"
  | "commercial.underwrite"
  | "commercial.market_research"
  | "commercial.product_improve"
  | "commercial.fraud_detect"
  | "commercial.resell"
  | "lifecycle.retain"
  | "lifecycle.delete"
  | "lifecycle.restrict"
  | "lifecycle.port";

export const OPERATION_ALL: readonly Operation[] = [
  "collect.observe",
  "collect.receive",
  "collect.generate",
  "store.persist",
  "store.replicate",
  "store.backup",
  "access.read",
  "access.query",
  "access.index",
  "access.export_view",
  "process.transform",
  "process.aggregate",
  "process.classify",
  "process.profile",
  "process.score",
  "process.personalize",
  "process.recommend",
  "process.predict",
  "process.match",
  "process.deidentify",
  "process.anonymize",
  "process.dp_release",
  "transfer.internal",
  "transfer.affiliate",
  "transfer.processor",
  "transfer.controller",
  "transfer.sale",
  "transfer.license",
  "transfer.api_access",
  "transfer.export_jurisdiction",
  "transfer.publish",
  "ai.pretrain",
  "ai.finetune",
  "ai.instruction_tune",
  "ai.preference_data",
  "ai.rl_environment",
  "ai.embed",
  "ai.index_retrieval",
  "ai.retrieve",
  "ai.inference_input",
  "ai.evaluate",
  "ai.synthesize",
  "ai.distill",
  "ai.unlearn",
  "commercial.advertise",
  "commercial.measure",
  "commercial.price",
  "commercial.underwrite",
  "commercial.market_research",
  "commercial.product_improve",
  "commercial.fraud_detect",
  "commercial.resell",
  "lifecycle.retain",
  "lifecycle.delete",
  "lifecycle.restrict",
  "lifecycle.port",
];

/** Purposes. */
export type Purpose =
  | "service"
  | "service.core"
  | "service.account"
  | "service.support"
  | "service.personalization"
  | "security"
  | "security.fraud"
  | "security.abuse"
  | "security.authentication"
  | "legal"
  | "legal.obligation"
  | "legal.claims"
  | "legal.audit"
  | "operations"
  | "operations.reliability"
  | "operations.capacity"
  | "improvement"
  | "improvement.analytics"
  | "improvement.experimentation"
  | "improvement.ai_training"
  | "improvement.ai_evaluation"
  | "marketing"
  | "marketing.direct"
  | "marketing.advertising"
  | "marketing.advertising.contextual"
  | "marketing.advertising.behavioral"
  | "marketing.measurement"
  | "commerce"
  | "commerce.sale"
  | "commerce.licensing"
  | "commerce.brokerage"
  | "risk"
  | "risk.credit"
  | "risk.insurance"
  | "risk.pricing"
  | "research"
  | "research.scientific"
  | "research.public_interest"
  | "research.commercial";

export const PURPOSE_ALL: readonly Purpose[] = [
  "service",
  "service.core",
  "service.account",
  "service.support",
  "service.personalization",
  "security",
  "security.fraud",
  "security.abuse",
  "security.authentication",
  "legal",
  "legal.obligation",
  "legal.claims",
  "legal.audit",
  "operations",
  "operations.reliability",
  "operations.capacity",
  "improvement",
  "improvement.analytics",
  "improvement.experimentation",
  "improvement.ai_training",
  "improvement.ai_evaluation",
  "marketing",
  "marketing.direct",
  "marketing.advertising",
  "marketing.advertising.contextual",
  "marketing.advertising.behavioral",
  "marketing.measurement",
  "commerce",
  "commerce.sale",
  "commerce.licensing",
  "commerce.brokerage",
  "risk",
  "risk.credit",
  "risk.insurance",
  "risk.pricing",
  "research",
  "research.scientific",
  "research.public_interest",
  "research.commercial",
];

/** Regulatory regime tags. */
export type Regime =
  | "eu.gdpr"
  | "eu.data_act"
  | "eu.ai_act"
  | "uk.uk_gdpr"
  | "us.ca.ccpa"
  | "us.co.cpa"
  | "us.va.vcdpa"
  | "us.hipaa"
  | "us.glba"
  | "us.fcra"
  | "us.coppa"
  | "us.ferpa"
  | "us.il.bipa"
  | "br.lgpd"
  | "ca.pipeda"
  | "jp.appi"
  | "kr.pipa"
  | "in.dpdp"
  | "cn.pipl"
  | "au.privacy_act"
  | "za.popia";

export const REGIME_ALL: readonly Regime[] = [
  "eu.gdpr",
  "eu.data_act",
  "eu.ai_act",
  "uk.uk_gdpr",
  "us.ca.ccpa",
  "us.co.cpa",
  "us.va.vcdpa",
  "us.hipaa",
  "us.glba",
  "us.fcra",
  "us.coppa",
  "us.ferpa",
  "us.il.bipa",
  "br.lgpd",
  "ca.pipeda",
  "jp.appi",
  "kr.pipa",
  "in.dpdp",
  "cn.pipl",
  "au.privacy_act",
  "za.popia",
];

/** Lawful-basis assertions. */
export type LawfulBasis =
  | "consent"
  | "contract"
  | "legal_obligation"
  | "vital_interests"
  | "public_task"
  | "legitimate_interests"
  | "opt_out_respected"
  | "protocol_authorization";

export const LAWFULBASIS_ALL: readonly LawfulBasis[] = [
  "consent",
  "contract",
  "legal_obligation",
  "vital_interests",
  "public_task",
  "legitimate_interests",
  "opt_out_respected",
  "protocol_authorization",
];

export const TIER_RANK: Record<SensitivityTier, number> = {
  "t0": 0,
  "t1": 1,
  "t2": 2,
  "t3": 3,
  "t4": 4,
};

export const DATA_CLASS_SENSITIVITY: Record<DataClass, SensitivityTier> = {
  "identity.direct": "t3",
  "identity.pseudonymous": "t2",
  "identity.government": "t4",
  "contact.email": "t2",
  "contact.phone": "t2",
  "contact.postal": "t3",
  "location.precise": "t4",
  "location.coarse": "t2",
  "location.inferred_home": "t4",
  "location.inferred_work": "t3",
  "location.trajectory": "t4",
  "device.identifier": "t2",
  "device.fingerprint": "t3",
  "device.configuration": "t1",
  "device.network": "t2",
  "behavior.web_browsing": "t2",
  "behavior.app_usage": "t2",
  "behavior.search": "t3",
  "behavior.content_consumption": "t2",
  "behavior.social_graph": "t3",
  "behavior.keystroke_dynamics": "t3",
  "behavior.attention": "t3",
  "transaction.purchase": "t2",
  "transaction.payment_instrument": "t4",
  "financial.account": "t4",
  "financial.creditworthiness": "t4",
  "financial.income": "t3",
  "content.user_generated": "t3",
  "content.communications": "t4",
  "content.media": "t3",
  "biometric.template": "t4",
  "biometric.derived": "t4",
  "health.clinical": "t4",
  "health.wearable": "t3",
  "health.inferred": "t4",
  "protected.race_ethnicity": "t4",
  "protected.religion": "t4",
  "protected.political": "t4",
  "protected.sexual_orientation": "t4",
  "protected.genetic": "t4",
  "protected.immigration": "t4",
  "minor.any": "t4",
  "education.record": "t3",
  "employment.record": "t3",
  "telemetry.enterprise": "t1",
  "telemetry.security": "t2",
  "telemetry.vehicle": "t3",
  "telemetry.iot_home": "t3",
  "telemetry.iot_industrial": "t0",
  "sensor.environmental": "t0",
  "sensor.imaging_public": "t3",
  "industrial.process": "t0",
  "scientific.measurement": "t0",
  "scientific.human_subject": "t4",
  "derived.profile": "t3",
  "derived.segment": "t2",
  "derived.embedding": "t3",
  "derived.aggregate": "t1",
  "derived.dp_aggregate": "t0",
  "derived.synthetic": "t1",
  "derived.model_parameters": "t2",
};

export const DATA_CLASS_REID_RISK: Record<DataClass, number> = {
  "identity.direct": 95,
  "identity.pseudonymous": 60,
  "identity.government": 98,
  "contact.email": 85,
  "contact.phone": 88,
  "contact.postal": 80,
  "location.precise": 92,
  "location.coarse": 45,
  "location.inferred_home": 90,
  "location.inferred_work": 78,
  "location.trajectory": 96,
  "device.identifier": 70,
  "device.fingerprint": 82,
  "device.configuration": 35,
  "device.network": 66,
  "behavior.web_browsing": 72,
  "behavior.app_usage": 64,
  "behavior.search": 80,
  "behavior.content_consumption": 58,
  "behavior.social_graph": 86,
  "behavior.keystroke_dynamics": 84,
  "behavior.attention": 70,
  "transaction.purchase": 68,
  "transaction.payment_instrument": 90,
  "financial.account": 88,
  "financial.creditworthiness": 85,
  "financial.income": 75,
  "content.user_generated": 76,
  "content.communications": 90,
  "content.media": 82,
  "biometric.template": 99,
  "biometric.derived": 88,
  "health.clinical": 94,
  "health.wearable": 80,
  "health.inferred": 86,
  "protected.race_ethnicity": 70,
  "protected.religion": 70,
  "protected.political": 72,
  "protected.sexual_orientation": 74,
  "protected.genetic": 99,
  "protected.immigration": 76,
  "minor.any": 80,
  "education.record": 78,
  "employment.record": 80,
  "telemetry.enterprise": 25,
  "telemetry.security": 55,
  "telemetry.vehicle": 80,
  "telemetry.iot_home": 74,
  "telemetry.iot_industrial": 5,
  "sensor.environmental": 3,
  "sensor.imaging_public": 70,
  "industrial.process": 4,
  "scientific.measurement": 4,
  "scientific.human_subject": 88,
  "derived.profile": 84,
  "derived.segment": 50,
  "derived.embedding": 65,
  "derived.aggregate": 12,
  "derived.dp_aggregate": 2,
  "derived.synthetic": 20,
  "derived.model_parameters": 40,
};

export const OPERATION_METER: Record<Operation, Unit> = {
  "collect.observe": "record",
  "collect.receive": "record",
  "collect.generate": "record",
  "store.persist": "subject_day",
  "store.replicate": "subject_day",
  "store.backup": "subject_day",
  "access.read": "record",
  "access.query": "query",
  "access.index": "record",
  "access.export_view": "record",
  "process.transform": "record",
  "process.aggregate": "record",
  "process.classify": "inference",
  "process.profile": "inference",
  "process.score": "inference",
  "process.personalize": "inference",
  "process.recommend": "inference",
  "process.predict": "inference",
  "process.match": "record",
  "process.deidentify": "record",
  "process.anonymize": "record",
  "process.dp_release": "query",
  "transfer.internal": "record",
  "transfer.affiliate": "record",
  "transfer.processor": "record",
  "transfer.controller": "record",
  "transfer.sale": "record",
  "transfer.license": "record",
  "transfer.api_access": "query",
  "transfer.export_jurisdiction": "record",
  "transfer.publish": "record",
  "ai.pretrain": "token",
  "ai.finetune": "token",
  "ai.instruction_tune": "token",
  "ai.preference_data": "comparison",
  "ai.rl_environment": "episode",
  "ai.embed": "record",
  "ai.index_retrieval": "record",
  "ai.retrieve": "retrieval",
  "ai.inference_input": "inference",
  "ai.evaluate": "record",
  "ai.synthesize": "record",
  "ai.distill": "token",
  "ai.unlearn": "record",
  "commercial.advertise": "impression",
  "commercial.measure": "impression",
  "commercial.price": "inference",
  "commercial.underwrite": "inference",
  "commercial.market_research": "record",
  "commercial.product_improve": "record",
  "commercial.fraud_detect": "inference",
  "commercial.resell": "record",
  "lifecycle.retain": "subject_day",
  "lifecycle.delete": "record",
  "lifecycle.restrict": "record",
  "lifecycle.port": "record",
};

export const OPERATION_DERIVES: Record<Operation, boolean> = {
  "collect.observe": false,
  "collect.receive": false,
  "collect.generate": true,
  "store.persist": false,
  "store.replicate": false,
  "store.backup": false,
  "access.read": false,
  "access.query": false,
  "access.index": true,
  "access.export_view": true,
  "process.transform": true,
  "process.aggregate": true,
  "process.classify": true,
  "process.profile": true,
  "process.score": true,
  "process.personalize": false,
  "process.recommend": false,
  "process.predict": true,
  "process.match": true,
  "process.deidentify": true,
  "process.anonymize": true,
  "process.dp_release": true,
  "transfer.internal": false,
  "transfer.affiliate": false,
  "transfer.processor": false,
  "transfer.controller": false,
  "transfer.sale": false,
  "transfer.license": false,
  "transfer.api_access": false,
  "transfer.export_jurisdiction": false,
  "transfer.publish": false,
  "ai.pretrain": true,
  "ai.finetune": true,
  "ai.instruction_tune": true,
  "ai.preference_data": true,
  "ai.rl_environment": true,
  "ai.embed": true,
  "ai.index_retrieval": true,
  "ai.retrieve": false,
  "ai.inference_input": false,
  "ai.evaluate": true,
  "ai.synthesize": true,
  "ai.distill": true,
  "ai.unlearn": true,
  "commercial.advertise": false,
  "commercial.measure": false,
  "commercial.price": false,
  "commercial.underwrite": false,
  "commercial.market_research": false,
  "commercial.product_improve": false,
  "commercial.fraud_detect": false,
  "commercial.resell": false,
  "lifecycle.retain": false,
  "lifecycle.delete": false,
  "lifecycle.restrict": false,
  "lifecycle.port": false,
};

export const UNIT_ADDITIVE: Record<Unit, boolean> = {
  "record": true,
  "byte": true,
  "subject_day": true,
  "query": true,
  "inference": true,
  "impression": true,
  "token": true,
  "comparison": true,
  "episode": true,
  "retrieval": true,
  "gradient_step": true,
  "share": false,
};

export const PURPOSE_PARENT: Record<Purpose, Purpose | null> = {
  "service": null,
  "service.core": "service",
  "service.account": "service",
  "service.support": "service",
  "service.personalization": "service",
  "security": null,
  "security.fraud": "security",
  "security.abuse": "security",
  "security.authentication": "security",
  "legal": null,
  "legal.obligation": "legal",
  "legal.claims": "legal",
  "legal.audit": "legal",
  "operations": null,
  "operations.reliability": "operations",
  "operations.capacity": "operations",
  "improvement": null,
  "improvement.analytics": "improvement",
  "improvement.experimentation": "improvement",
  "improvement.ai_training": "improvement",
  "improvement.ai_evaluation": "improvement",
  "marketing": null,
  "marketing.direct": "marketing",
  "marketing.advertising": "marketing",
  "marketing.advertising.contextual": "marketing.advertising",
  "marketing.advertising.behavioral": "marketing.advertising",
  "marketing.measurement": "marketing",
  "commerce": null,
  "commerce.sale": "commerce",
  "commerce.licensing": "commerce",
  "commerce.brokerage": "commerce",
  "risk": null,
  "risk.credit": "risk",
  "risk.insurance": "risk",
  "risk.pricing": "risk",
  "research": null,
  "research.scientific": "research",
  "research.public_interest": "research",
  "research.commercial": "research",
};

export const PURPOSE_COMMERCIAL: Record<Purpose, boolean> = {
  "service": false,
  "service.core": false,
  "service.account": false,
  "service.support": false,
  "service.personalization": false,
  "security": false,
  "security.fraud": false,
  "security.abuse": false,
  "security.authentication": false,
  "legal": false,
  "legal.obligation": false,
  "legal.claims": false,
  "legal.audit": false,
  "operations": false,
  "operations.reliability": false,
  "operations.capacity": false,
  "improvement": true,
  "improvement.analytics": true,
  "improvement.experimentation": true,
  "improvement.ai_training": true,
  "improvement.ai_evaluation": true,
  "marketing": true,
  "marketing.direct": true,
  "marketing.advertising": true,
  "marketing.advertising.contextual": true,
  "marketing.advertising.behavioral": true,
  "marketing.measurement": true,
  "commerce": true,
  "commerce.sale": true,
  "commerce.licensing": true,
  "commerce.brokerage": true,
  "risk": true,
  "risk.credit": true,
  "risk.insurance": true,
  "risk.pricing": true,
  "research": false,
  "research.scientific": false,
  "research.public_interest": false,
  "research.commercial": true,
};

/** True if `broad` is `narrow` or an ancestor of it in the purpose lattice. */
export function purposeCovers(broad: Purpose, narrow: Purpose): boolean {
  let cur: Purpose | null = narrow;
  while (cur !== null) {
    if (cur === broad) return true;
    cur = PURPOSE_PARENT[cur];
  }
  return false;
}
