#!/usr/bin/env python3
"""Generate typed taxonomy code for every DUAP SDK from the ontology JSON.

One ontology, four languages. Divergence between SDK taxonomies would be an
interoperability break that no amount of testing on one side would catch, so
the enums are never hand-written. CI runs this with --check.
"""
import json, pathlib, sys, hashlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ONT = json.loads((ROOT / "ontology" / "duap-ontology-v1.json").read_text())
ONT_BYTES = (ROOT / "ontology" / "duap-ontology-v1.json").read_bytes()
ONT_HASH = hashlib.sha256(ONT_BYTES).hexdigest()

BANNER_LINES = [
    "DO NOT EDIT. Generated by ontology/gen_code.py from",
    "ontology/duap-ontology-v1.json (sha256 " + ONT_HASH[:32] + "...).",
    "Edit the ontology and regenerate; CI fails if this file is stale.",
]


def variant(code):
    return "".join(p.capitalize() for part in code.split(".") for p in part.split("_"))


def snake(code):
    return code.replace(".", "_").replace("-", "_")


def screaming(code):
    return snake(code).upper()


def esc(s):
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


# ---------------------------------------------------------------------------
# Rust
# ---------------------------------------------------------------------------
def rust_enum(name, items, doc, extra_methods=""):
    out = [f"/// {doc}"]
    out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]")
    out.append('#[serde(try_from = "String", into = "String")]')
    out.append(f"pub enum {name} {{")
    for it in items:
        d = it.get("name", it["code"])
        out.append(f"    /// `{it['code']}` -- {d}")
        if it.get("notes"):
            out.append(f"    ///")
            out.append(f"    /// {esc(it['notes'])}")
        out.append(f"    {variant(it['code'])},")
    out.append("}")
    out.append("")
    out.append(f"impl {name} {{")
    out.append(f"    /// Every registered {name} value, in ontology order.")
    out.append(f"    pub const ALL: [{name}; {len(items)}] = [")
    for it in items:
        out.append(f"        {name}::{variant(it['code'])},")
    out.append("    ];")
    out.append("")
    out.append("    /// The ontology code.")
    out.append("    pub const fn code(self) -> &'static str {")
    out.append("        match self {")
    for it in items:
        out.append(f'            {name}::{variant(it["code"])} => "{it["code"]}",')
    out.append("        }")
    out.append("    }")
    out.append("")
    out.append("    /// Human-readable label.")
    out.append("    pub const fn label(self) -> &'static str {")
    out.append("        match self {")
    for it in items:
        out.append(f'            {name}::{variant(it["code"])} => "{esc(it.get("name", it["code"]))}",')
    out.append("        }")
    out.append("    }")
    out.append("")
    out.append("    /// Parse an ontology code.")
    out.append("    pub fn parse(s: &str) -> Result<Self, TaxonomyError> {")
    out.append("        match s {")
    for it in items:
        out.append(f'            "{it["code"]}" => Ok({name}::{variant(it["code"])}),')
    out.append(f'            other => Err(TaxonomyError::UnknownCode {{ kind: "{name}", code: other.to_owned() }}),')
    out.append("        }")
    out.append("    }")
    out.append(extra_methods)
    out.append("}")
    out.append("")
    out.append(f"impl std::fmt::Display for {name} {{")
    out.append("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
    out.append("        f.write_str(self.code())")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append(f"impl std::str::FromStr for {name} {{")
    out.append("    type Err = TaxonomyError;")
    out.append("    fn from_str(s: &str) -> Result<Self, TaxonomyError> { Self::parse(s) }")
    out.append("}")
    out.append("")
    out.append(f"impl TryFrom<String> for {name} {{")
    out.append("    type Error = TaxonomyError;")
    out.append("    fn try_from(s: String) -> Result<Self, TaxonomyError> { Self::parse(&s) }")
    out.append("}")
    out.append("")
    out.append(f"impl From<{name}> for String {{")
    out.append(f"    fn from(v: {name}) -> String {{ v.code().to_owned() }}")
    out.append("}")
    out.append("")
    return "\n".join(out)


def gen_rust():
    L = []
    for b in BANNER_LINES:
        L.append(f"// {b}")
    L.append("")
    L.append("//! Typed DUAP taxonomy: data classes, operations, purposes, units,")
    L.append("//! collection methods, sensitivity tiers, regimes and lawful bases.")
    L.append("//!")
    L.append("//! STATUS: PRODUCTION (generated).")
    L.append("")
    L.append("#![allow(clippy::match_like_matches_macro)]")
    L.append("")
    L.append("use serde::{Deserialize, Serialize};")
    L.append("use crate::error::TaxonomyError;")
    L.append("")
    L.append(f'/// Version of the ontology these definitions were generated from.')
    L.append(f'pub const ONTOLOGY_VERSION: &str = "{ONT["ontology_version"]}";')
    L.append(f'/// SHA-256 of the ontology document, for cross-implementation checks.')
    L.append(f'pub const ONTOLOGY_SHA256: &str = "{ONT_HASH}";')
    L.append("")

    # sensitivity tier
    tiers = ONT["sensitivity_tiers"]
    extra = ["", "    /// Ordinal rank; higher means more sensitive.",
             "    pub const fn rank(self) -> u8 {", "        match self {"]
    for t in tiers:
        extra.append(f"            SensitivityTier::{variant(t['code'])} => {t['rank']},")
    extra += ["        }", "    }"]
    L.append(rust_enum("SensitivityTier", tiers,
                       "How much harm disclosure of this data would do to the subject.",
                       "\n".join(extra)))

    # data classes
    dcs = ONT["data_classes"]
    extra = ["", "    /// Default sensitivity tier for this class.",
             "    pub const fn sensitivity(self) -> SensitivityTier {", "        match self {"]
    for d in dcs:
        extra.append(f"            DataClass::{variant(d['code'])} => SensitivityTier::{variant(d['sensitivity'])},")
    extra += ["        }", "    }", "",
              "    /// Prior for the re-identification risk of one record of this class,",
              "    /// on a 0-100 scale. A parameter of the valuation model, not a",
              "    /// measurement; see `VALUATION.md` for the calibration procedure.",
              "    pub const fn reid_risk(self) -> u8 {", "        match self {"]
    for d in dcs:
        extra.append(f"            DataClass::{variant(d['code'])} => {d['reid_risk']},")
    extra += ["        }", "    }", "",
              "    /// Regime-specific special-category tags asserted for this class.",
              "    pub const fn special_categories(self) -> &'static [&'static str] {",
              "        match self {"]
    for d in dcs:
        arr = ", ".join(f'"{s}"' for s in d["special_category"])
        extra.append(f"            DataClass::{variant(d['code'])} => &[{arr}],")
    extra += ["        }", "    }", "",
              "    /// Whether any regime tags this class as a special category.",
              "    pub const fn is_special_category(self) -> bool {",
              "        !self.special_categories().is_empty()", "    }",
              "",
              "    /// The dotted namespace prefix, e.g. `location` for `location.precise`.",
              "    pub fn namespace(self) -> &'static str {",
              "        let c = self.code();",
              "        match c.find('.') { Some(i) => &c[..i], None => c }",
              "    }"]
    L.append(rust_enum("DataClass", dcs, "A class of data in the DUAP taxonomy.", "\n".join(extra)))

    # collection methods
    cms = ONT["collection_methods"]
    extra = ["", "    /// Whether a data subject can in principle detect this collection",
             "    /// locally. Used by the participant dashboard to flag collection the",
             "    /// subject has no way of observing without the protocol.",
             "    pub const fn subject_observable(self) -> bool {", "        match self {"]
    for c in cms:
        extra.append(f"            CollectionMethod::{variant(c['code'])} => {str(c['subject_observable']).lower()},")
    extra += ["        }", "    }"]
    L.append(rust_enum("CollectionMethod", cms, "How data was obtained.", "\n".join(extra)))

    # units
    units = ONT["units"]
    extra = ["", "    /// Whether quantities in this unit may be summed across events.",
             "    ///",
             "    /// Non-additive units (attribution shares) must be combined with the",
             "    /// scope-aware rules in `duap-valuation`, never added.",
             "    pub const fn additive(self) -> bool {", "        match self {"]
    for u in units:
        extra.append(f"            Unit::{variant(u['code'])} => {str(u['additive']).lower()},")
    extra += ["        }", "    }"]
    L.append(rust_enum("Unit", units, "A measurement unit for metered quantities.", "\n".join(extra)))

    # operations
    ops = ONT["operations"]
    fams = sorted({o["family"] for o in ops})
    L.append("/// Top-level operation families.")
    L.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]")
    L.append('#[serde(rename_all = "snake_case")]')
    L.append("pub enum OperationFamily {")
    for f in fams:
        L.append(f"    {variant(f)},")
    L.append("}")
    L.append("")
    L.append("impl OperationFamily {")
    L.append("    pub const fn code(self) -> &'static str {")
    L.append("        match self {")
    for f in fams:
        L.append(f'            OperationFamily::{variant(f)} => "{f}",')
    L.append("        }")
    L.append("    }")
    L.append("}")
    L.append("")
    extra = ["", "    /// Operation family.",
             "    pub const fn family(self) -> OperationFamily {", "        match self {"]
    for o in ops:
        extra.append(f"            Operation::{variant(o['code'])} => OperationFamily::{variant(o['family'])},")
    extra += ["        }", "    }", "",
              "    /// The unit this operation is naturally metered in.",
              "    pub const fn meter(self) -> Unit {", "        match self {"]
    for o in ops:
        extra.append(f"            Operation::{variant(o['code'])} => Unit::{variant(o['meter'])},")
    extra += ["        }", "    }", "",
              "    /// Whether the operation can produce a derived object whose rights",
              "    /// must be propagated through the provenance graph.",
              "    pub const fn derives(self) -> bool {", "        match self {"]
    for o in ops:
        extra.append(f"            Operation::{variant(o['code'])} => {str(o['derives']).lower()},")
    extra += ["        }", "    }"]
    L.append(rust_enum("Operation", ops, "An operation performed on data.", "\n".join(extra)))

    # purposes with lattice
    pus = ONT["purposes"]
    extra = ["", "    /// The parent purpose in the lattice, if any.",
             "    pub const fn parent(self) -> Option<Purpose> {", "        match self {"]
    for p in pus:
        if p["parent"]:
            extra.append(f"            Purpose::{variant(p['code'])} => Some(Purpose::{variant(p['parent'])}),")
        else:
            extra.append(f"            Purpose::{variant(p['code'])} => None,")
    extra += ["        }", "    }", "",
              "    /// Whether this purpose is a commercial exploitation of the data.",
              "    /// Drives the default pricing model and several policy defaults.",
              "    pub const fn commercial(self) -> bool {", "        match self {"]
    for p in pus:
        extra.append(f"            Purpose::{variant(p['code'])} => {str(p['commercial']).lower()},")
    extra += ["        }", "    }", "",
              "    /// Whether `self` is `other` or an ancestor of it.",
              "    ///",
              "    /// Purpose limitation is decided by this relation. A grant for",
              "    /// `marketing` covers `marketing.advertising.behavioral`; a grant for",
              "    /// `marketing.advertising.contextual` does not.",
              "    pub fn covers(self, other: Purpose) -> bool {",
              "        let mut cur = Some(other);",
              "        while let Some(p) = cur {",
              "            if p == self { return true; }",
              "            cur = p.parent();",
              "        }",
              "        false",
              "    }",
              "",
              "    /// Distance to the root of the lattice.",
              "    pub fn depth(self) -> usize {",
              "        let mut d = 0; let mut cur = self.parent();",
              "        while let Some(p) = cur { d += 1; cur = p.parent(); }",
              "        d",
              "    }"]
    L.append(rust_enum("Purpose", pus, "A purpose of processing, forming a lattice.", "\n".join(extra)))

    L.append(rust_enum("Regime", ONT["regimes"],
                       "A regulatory regime tag. A recording category, not a legal determination."))
    L.append(rust_enum("LawfulBasis", ONT["lawful_bases"],
                       "A lawful-basis assertion made by the controller."))
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------
# Python
# ---------------------------------------------------------------------------
def gen_python():
    L = ['"""' + BANNER_LINES[0]]
    for b in BANNER_LINES[1:]:
        L.append(b)
    L.append("")
    L.append("Typed DUAP taxonomy for the Python SDK.")
    L.append('"""')
    L.append("")
    L.append("from __future__ import annotations")
    L.append("")
    L.append("from enum import Enum")
    L.append("from typing import Optional")
    L.append("")
    L.append(f'ONTOLOGY_VERSION = "{ONT["ontology_version"]}"')
    L.append(f'ONTOLOGY_SHA256 = "{ONT_HASH}"')
    L.append("")

    def pyenum(name, items, doc):
        out = [f"class {name}(str, Enum):", f'    """{doc}"""', ""]
        for it in items:
            out.append(f'    {screaming(it["code"])} = "{it["code"]}"')
        out.append("")
        return "\n".join(out)

    L.append(pyenum("SensitivityTier", ONT["sensitivity_tiers"], "Sensitivity tiers."))
    L.append(pyenum("DataClass", ONT["data_classes"], "Data classes."))
    L.append(pyenum("CollectionMethod", ONT["collection_methods"], "Collection methods."))
    L.append(pyenum("Unit", ONT["units"], "Measurement units."))
    L.append(pyenum("Operation", ONT["operations"], "Operations."))
    L.append(pyenum("Purpose", ONT["purposes"], "Purposes."))
    L.append(pyenum("Regime", ONT["regimes"], "Regulatory regime tags."))
    L.append(pyenum("LawfulBasis", ONT["lawful_bases"], "Lawful-basis assertions."))

    L.append("TIER_RANK = {")
    for t in ONT["sensitivity_tiers"]:
        L.append(f'    SensitivityTier.{screaming(t["code"])}: {t["rank"]},')
    L.append("}")
    L.append("")
    L.append("DATA_CLASS_SENSITIVITY = {")
    for d in ONT["data_classes"]:
        L.append(f'    DataClass.{screaming(d["code"])}: SensitivityTier.{screaming(d["sensitivity"])},')
    L.append("}")
    L.append("")
    L.append("DATA_CLASS_REID_RISK = {")
    for d in ONT["data_classes"]:
        L.append(f'    DataClass.{screaming(d["code"])}: {d["reid_risk"]},')
    L.append("}")
    L.append("")
    L.append("DATA_CLASS_SPECIAL = {")
    for d in ONT["data_classes"]:
        L.append(f'    DataClass.{screaming(d["code"])}: {d["special_category"]!r},')
    L.append("}")
    L.append("")
    L.append("OPERATION_METER = {")
    for o in ONT["operations"]:
        L.append(f'    Operation.{screaming(o["code"])}: Unit.{screaming(o["meter"])},')
    L.append("}")
    L.append("")
    L.append("OPERATION_DERIVES = {")
    for o in ONT["operations"]:
        L.append(f'    Operation.{screaming(o["code"])}: {o["derives"]},')
    L.append("}")
    L.append("")
    L.append("OPERATION_FAMILY = {")
    for o in ONT["operations"]:
        L.append(f'    Operation.{screaming(o["code"])}: "{o["family"]}",')
    L.append("}")
    L.append("")
    L.append("UNIT_ADDITIVE = {")
    for u in ONT["units"]:
        L.append(f'    Unit.{screaming(u["code"])}: {u["additive"]},')
    L.append("}")
    L.append("")
    L.append("PURPOSE_PARENT: dict[Purpose, Optional[Purpose]] = {")
    for p in ONT["purposes"]:
        par = f'Purpose.{screaming(p["parent"])}' if p["parent"] else "None"
        L.append(f'    Purpose.{screaming(p["code"])}: {par},')
    L.append("}")
    L.append("")
    L.append("PURPOSE_COMMERCIAL = {")
    for p in ONT["purposes"]:
        L.append(f'    Purpose.{screaming(p["code"])}: {p["commercial"]},')
    L.append("}")
    L.append("")
    L.append('''

def purpose_covers(broad: Purpose, narrow: Purpose) -> bool:
    """True if `broad` is `narrow` or an ancestor of it in the purpose lattice."""
    cur: Optional[Purpose] = narrow
    while cur is not None:
        if cur == broad:
            return True
        cur = PURPOSE_PARENT[cur]
    return False
''')
    return "\n".join(L)


# ---------------------------------------------------------------------------
# TypeScript
# ---------------------------------------------------------------------------
def gen_typescript():
    L = ["/**"]
    for b in BANNER_LINES:
        L.append(" * " + b)
    L.append(" */")
    L.append("")
    L.append(f'export const ONTOLOGY_VERSION = "{ONT["ontology_version"]}";')
    L.append(f'export const ONTOLOGY_SHA256 = "{ONT_HASH}";')
    L.append("")

    def tsunion(name, items, doc):
        out = [f"/** {doc} */", f"export type {name} ="]
        for i, it in enumerate(items):
            sep = ";" if i == len(items) - 1 else ""
            out.append(f'  | "{it["code"]}"{sep}')
        out.append("")
        out.append(f"export const {screaming(name)}_ALL: readonly {name}[] = [")
        for it in items:
            out.append(f'  "{it["code"]}",')
        out.append("];")
        out.append("")
        return "\n".join(out)

    L.append(tsunion("SensitivityTier", ONT["sensitivity_tiers"], "Sensitivity tiers."))
    L.append(tsunion("DataClass", ONT["data_classes"], "Data classes."))
    L.append(tsunion("CollectionMethod", ONT["collection_methods"], "Collection methods."))
    L.append(tsunion("Unit", ONT["units"], "Measurement units."))
    L.append(tsunion("Operation", ONT["operations"], "Operations."))
    L.append(tsunion("Purpose", ONT["purposes"], "Purposes."))
    L.append(tsunion("Regime", ONT["regimes"], "Regulatory regime tags."))
    L.append(tsunion("LawfulBasis", ONT["lawful_bases"], "Lawful-basis assertions."))

    L.append("export const TIER_RANK: Record<SensitivityTier, number> = {")
    for t in ONT["sensitivity_tiers"]:
        L.append(f'  "{t["code"]}": {t["rank"]},')
    L.append("};")
    L.append("")
    L.append("export const DATA_CLASS_SENSITIVITY: Record<DataClass, SensitivityTier> = {")
    for d in ONT["data_classes"]:
        L.append(f'  "{d["code"]}": "{d["sensitivity"]}",')
    L.append("};")
    L.append("")
    L.append("export const DATA_CLASS_REID_RISK: Record<DataClass, number> = {")
    for d in ONT["data_classes"]:
        L.append(f'  "{d["code"]}": {d["reid_risk"]},')
    L.append("};")
    L.append("")
    L.append("export const OPERATION_METER: Record<Operation, Unit> = {")
    for o in ONT["operations"]:
        L.append(f'  "{o["code"]}": "{o["meter"]}",')
    L.append("};")
    L.append("")
    L.append("export const OPERATION_DERIVES: Record<Operation, boolean> = {")
    for o in ONT["operations"]:
        L.append(f'  "{o["code"]}": {str(o["derives"]).lower()},')
    L.append("};")
    L.append("")
    L.append("export const UNIT_ADDITIVE: Record<Unit, boolean> = {")
    for u in ONT["units"]:
        L.append(f'  "{u["code"]}": {str(u["additive"]).lower()},')
    L.append("};")
    L.append("")
    L.append("export const PURPOSE_PARENT: Record<Purpose, Purpose | null> = {")
    for p in ONT["purposes"]:
        par = f'"{p["parent"]}"' if p["parent"] else "null"
        L.append(f'  "{p["code"]}": {par},')
    L.append("};")
    L.append("")
    L.append("export const PURPOSE_COMMERCIAL: Record<Purpose, boolean> = {")
    for p in ONT["purposes"]:
        L.append(f'  "{p["code"]}": {str(p["commercial"]).lower()},')
    L.append("};")
    L.append("")
    L.append("""/** True if `broad` is `narrow` or an ancestor of it in the purpose lattice. */
export function purposeCovers(broad: Purpose, narrow: Purpose): boolean {
  let cur: Purpose | null = narrow;
  while (cur !== null) {
    if (cur === broad) return true;
    cur = PURPOSE_PARENT[cur];
  }
  return false;
}
""")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Go
# ---------------------------------------------------------------------------
def gen_go():
    L = []
    for b in BANNER_LINES:
        L.append("// " + b)
    L.append("")
    L.append("package taxonomy")
    L.append("")
    L.append(f'const OntologyVersion = "{ONT["ontology_version"]}"')
    L.append(f'const OntologySHA256 = "{ONT_HASH}"')
    L.append("")

    def gotype(name, items, doc):
        out = [f"// {name} is {doc}", f"type {name} string", "", "const ("]
        for it in items:
            out.append(f'\t{name}{variant(it["code"])} {name} = "{it["code"]}"')
        out.append(")")
        out.append("")
        out.append(f"// All{name}s lists every registered value, in ontology order.")
        out.append(f"var All{name}s = []{name}{{")
        for it in items:
            out.append(f'\t{name}{variant(it["code"])},')
        out.append("}")
        out.append("")
        out.append(f"// Valid reports whether v is a registered {name}.")
        out.append(f"func (v {name}) Valid() bool {{")
        out.append(f"\t_, ok := valid{name}[v]")
        out.append("\treturn ok")
        out.append("}")
        out.append("")
        out.append(f"var valid{name} = func() map[{name}]struct{{}} {{")
        out.append(f"\tm := make(map[{name}]struct{{}}, len(All{name}s))")
        out.append(f"\tfor _, v := range All{name}s {{")
        out.append("\t\tm[v] = struct{}{}")
        out.append("\t}")
        out.append("\treturn m")
        out.append("}()")
        out.append("")
        return "\n".join(out)

    L.append(gotype("SensitivityTier", ONT["sensitivity_tiers"], "a sensitivity tier."))
    L.append(gotype("DataClass", ONT["data_classes"], "a class of data."))
    L.append(gotype("CollectionMethod", ONT["collection_methods"], "how data was obtained."))
    L.append(gotype("Unit", ONT["units"], "a measurement unit."))
    L.append(gotype("Operation", ONT["operations"], "an operation on data."))
    L.append(gotype("Purpose", ONT["purposes"], "a purpose of processing."))
    L.append(gotype("Regime", ONT["regimes"], "a regulatory regime tag."))
    L.append(gotype("LawfulBasis", ONT["lawful_bases"], "a lawful-basis assertion."))

    L.append("// TierRank orders sensitivity tiers; higher means more sensitive.")
    L.append("var TierRank = map[SensitivityTier]int{")
    for t in ONT["sensitivity_tiers"]:
        L.append(f'\tSensitivityTier{variant(t["code"])}: {t["rank"]},')
    L.append("}")
    L.append("")
    L.append("// DataClassSensitivity gives the default tier for each class.")
    L.append("var DataClassSensitivity = map[DataClass]SensitivityTier{")
    for d in ONT["data_classes"]:
        L.append(f'\tDataClass{variant(d["code"])}: SensitivityTier{variant(d["sensitivity"])},')
    L.append("}")
    L.append("")
    L.append("// DataClassReidRisk gives the re-identification prior on a 0-100 scale.")
    L.append("var DataClassReidRisk = map[DataClass]int{")
    for d in ONT["data_classes"]:
        L.append(f'\tDataClass{variant(d["code"])}: {d["reid_risk"]},')
    L.append("}")
    L.append("")
    L.append("// OperationMeter gives the natural unit for each operation.")
    L.append("var OperationMeter = map[Operation]Unit{")
    for o in ONT["operations"]:
        L.append(f'\tOperation{variant(o["code"])}: Unit{variant(o["meter"])},')
    L.append("}")
    L.append("")
    L.append("// OperationDerives reports whether an operation can create a derived object.")
    L.append("var OperationDerives = map[Operation]bool{")
    for o in ONT["operations"]:
        L.append(f'\tOperation{variant(o["code"])}: {str(o["derives"]).lower()},')
    L.append("}")
    L.append("")
    L.append("// UnitAdditive reports whether quantities may be summed.")
    L.append("var UnitAdditive = map[Unit]bool{")
    for u in ONT["units"]:
        L.append(f'\tUnit{variant(u["code"])}: {str(u["additive"]).lower()},')
    L.append("}")
    L.append("")
    L.append("// PurposeParent gives the parent in the purpose lattice (\"\" at a root).")
    L.append("var PurposeParent = map[Purpose]Purpose{")
    for p in ONT["purposes"]:
        par = f'Purpose{variant(p["parent"])}' if p["parent"] else '""'
        L.append(f'\tPurpose{variant(p["code"])}: {par},')
    L.append("}")
    L.append("")
    L.append("// PurposeCommercial reports whether a purpose is commercial exploitation.")
    L.append("var PurposeCommercial = map[Purpose]bool{")
    for p in ONT["purposes"]:
        L.append(f'\tPurpose{variant(p["code"])}: {str(p["commercial"]).lower()},')
    L.append("}")
    L.append("")
    L.append("""// PurposeCovers reports whether broad is narrow or an ancestor of it.
func PurposeCovers(broad, narrow Purpose) bool {
	cur := narrow
	for cur != "" {
		if cur == broad {
			return true
		}
		cur = PurposeParent[cur]
	}
	return false
}
""")
    return "\n".join(L)


TARGETS = {
    "crates/duap-model/src/taxonomy.rs": gen_rust,
    "sdk/python/duap/taxonomy.py": gen_python,
    "sdk/typescript/src/taxonomy.ts": gen_typescript,
    "gateway/internal/taxonomy/taxonomy.go": gen_go,
}

if __name__ == "__main__":
    check = "--check" in sys.argv
    stale = []
    for rel, fn in TARGETS.items():
        path = ROOT / rel
        text = fn()
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel} ({len(text.splitlines())} lines)")
    if check:
        if stale:
            print("stale generated files: " + ", ".join(stale), file=sys.stderr)
            sys.exit(1)
        print("all generated taxonomy files up to date")
