"""DO NOT EDIT. Generated by ontology/gen_code.py from
ontology/duap-ontology-v1.json (sha256 68fcb23de2d63a4f2a216df14e048d51...).
Edit the ontology and regenerate; CI fails if this file is stale.

Typed DUAP taxonomy for the Python SDK.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

ONTOLOGY_VERSION = "1.0.0-draft"
ONTOLOGY_SHA256 = "68fcb23de2d63a4f2a216df14e048d519fbac744e1dfdecb0f69bd80d4fe4a41"

class SensitivityTier(str, Enum):
    """Sensitivity tiers."""

    T0 = "t0"
    T1 = "t1"
    T2 = "t2"
    T3 = "t3"
    T4 = "t4"

class DataClass(str, Enum):
    """Data classes."""

    IDENTITY_DIRECT = "identity.direct"
    IDENTITY_PSEUDONYMOUS = "identity.pseudonymous"
    IDENTITY_GOVERNMENT = "identity.government"
    CONTACT_EMAIL = "contact.email"
    CONTACT_PHONE = "contact.phone"
    CONTACT_POSTAL = "contact.postal"
    LOCATION_PRECISE = "location.precise"
    LOCATION_COARSE = "location.coarse"
    LOCATION_INFERRED_HOME = "location.inferred_home"
    LOCATION_INFERRED_WORK = "location.inferred_work"
    LOCATION_TRAJECTORY = "location.trajectory"
    DEVICE_IDENTIFIER = "device.identifier"
    DEVICE_FINGERPRINT = "device.fingerprint"
    DEVICE_CONFIGURATION = "device.configuration"
    DEVICE_NETWORK = "device.network"
    BEHAVIOR_WEB_BROWSING = "behavior.web_browsing"
    BEHAVIOR_APP_USAGE = "behavior.app_usage"
    BEHAVIOR_SEARCH = "behavior.search"
    BEHAVIOR_CONTENT_CONSUMPTION = "behavior.content_consumption"
    BEHAVIOR_SOCIAL_GRAPH = "behavior.social_graph"
    BEHAVIOR_KEYSTROKE_DYNAMICS = "behavior.keystroke_dynamics"
    BEHAVIOR_ATTENTION = "behavior.attention"
    TRANSACTION_PURCHASE = "transaction.purchase"
    TRANSACTION_PAYMENT_INSTRUMENT = "transaction.payment_instrument"
    FINANCIAL_ACCOUNT = "financial.account"
    FINANCIAL_CREDITWORTHINESS = "financial.creditworthiness"
    FINANCIAL_INCOME = "financial.income"
    CONTENT_USER_GENERATED = "content.user_generated"
    CONTENT_COMMUNICATIONS = "content.communications"
    CONTENT_MEDIA = "content.media"
    BIOMETRIC_TEMPLATE = "biometric.template"
    BIOMETRIC_DERIVED = "biometric.derived"
    HEALTH_CLINICAL = "health.clinical"
    HEALTH_WEARABLE = "health.wearable"
    HEALTH_INFERRED = "health.inferred"
    PROTECTED_RACE_ETHNICITY = "protected.race_ethnicity"
    PROTECTED_RELIGION = "protected.religion"
    PROTECTED_POLITICAL = "protected.political"
    PROTECTED_SEXUAL_ORIENTATION = "protected.sexual_orientation"
    PROTECTED_GENETIC = "protected.genetic"
    PROTECTED_IMMIGRATION = "protected.immigration"
    MINOR_ANY = "minor.any"
    EDUCATION_RECORD = "education.record"
    EMPLOYMENT_RECORD = "employment.record"
    TELEMETRY_ENTERPRISE = "telemetry.enterprise"
    TELEMETRY_SECURITY = "telemetry.security"
    TELEMETRY_VEHICLE = "telemetry.vehicle"
    TELEMETRY_IOT_HOME = "telemetry.iot_home"
    TELEMETRY_IOT_INDUSTRIAL = "telemetry.iot_industrial"
    SENSOR_ENVIRONMENTAL = "sensor.environmental"
    SENSOR_IMAGING_PUBLIC = "sensor.imaging_public"
    INDUSTRIAL_PROCESS = "industrial.process"
    SCIENTIFIC_MEASUREMENT = "scientific.measurement"
    SCIENTIFIC_HUMAN_SUBJECT = "scientific.human_subject"
    DERIVED_PROFILE = "derived.profile"
    DERIVED_SEGMENT = "derived.segment"
    DERIVED_EMBEDDING = "derived.embedding"
    DERIVED_AGGREGATE = "derived.aggregate"
    DERIVED_DP_AGGREGATE = "derived.dp_aggregate"
    DERIVED_SYNTHETIC = "derived.synthetic"
    DERIVED_MODEL_PARAMETERS = "derived.model_parameters"

class CollectionMethod(str, Enum):
    """Collection methods."""

    EXPLICIT_FORM = "explicit.form"
    EXPLICIT_UPLOAD = "explicit.upload"
    PASSIVE_COOKIE = "passive.cookie"
    PASSIVE_PIXEL = "passive.pixel"
    PASSIVE_SDK = "passive.sdk"
    PASSIVE_SERVER_LOG = "passive.server_log"
    PASSIVE_FINGERPRINT = "passive.fingerprint"
    PASSIVE_NETWORK = "passive.network"
    DEVICE_SENSOR = "device.sensor"
    DEVICE_OS_API = "device.os_api"
    OBSERVATION_CAMERA = "observation.camera"
    OBSERVATION_AUDIO = "observation.audio"
    MACHINE_VEHICLE_BUS = "machine.vehicle_bus"
    MACHINE_INDUSTRIAL_BUS = "machine.industrial_bus"
    ACQUISITION_THIRD_PARTY = "acquisition.third_party"
    ACQUISITION_BROKER = "acquisition.broker"
    ACQUISITION_PUBLIC = "acquisition.public"
    ACQUISITION_SCRAPE = "acquisition.scrape"
    INFERENCE_DERIVED = "inference.derived"

class Unit(str, Enum):
    """Measurement units."""

    RECORD = "record"
    BYTE = "byte"
    SUBJECT_DAY = "subject_day"
    QUERY = "query"
    INFERENCE = "inference"
    IMPRESSION = "impression"
    TOKEN = "token"
    COMPARISON = "comparison"
    EPISODE = "episode"
    RETRIEVAL = "retrieval"
    GRADIENT_STEP = "gradient_step"
    SHARE = "share"

class Operation(str, Enum):
    """Operations."""

    COLLECT_OBSERVE = "collect.observe"
    COLLECT_RECEIVE = "collect.receive"
    COLLECT_GENERATE = "collect.generate"
    STORE_PERSIST = "store.persist"
    STORE_REPLICATE = "store.replicate"
    STORE_BACKUP = "store.backup"
    ACCESS_READ = "access.read"
    ACCESS_QUERY = "access.query"
    ACCESS_INDEX = "access.index"
    ACCESS_EXPORT_VIEW = "access.export_view"
    PROCESS_TRANSFORM = "process.transform"
    PROCESS_AGGREGATE = "process.aggregate"
    PROCESS_CLASSIFY = "process.classify"
    PROCESS_PROFILE = "process.profile"
    PROCESS_SCORE = "process.score"
    PROCESS_PERSONALIZE = "process.personalize"
    PROCESS_RECOMMEND = "process.recommend"
    PROCESS_PREDICT = "process.predict"
    PROCESS_MATCH = "process.match"
    PROCESS_DEIDENTIFY = "process.deidentify"
    PROCESS_ANONYMIZE = "process.anonymize"
    PROCESS_DP_RELEASE = "process.dp_release"
    TRANSFER_INTERNAL = "transfer.internal"
    TRANSFER_AFFILIATE = "transfer.affiliate"
    TRANSFER_PROCESSOR = "transfer.processor"
    TRANSFER_CONTROLLER = "transfer.controller"
    TRANSFER_SALE = "transfer.sale"
    TRANSFER_LICENSE = "transfer.license"
    TRANSFER_API_ACCESS = "transfer.api_access"
    TRANSFER_EXPORT_JURISDICTION = "transfer.export_jurisdiction"
    TRANSFER_PUBLISH = "transfer.publish"
    AI_PRETRAIN = "ai.pretrain"
    AI_FINETUNE = "ai.finetune"
    AI_INSTRUCTION_TUNE = "ai.instruction_tune"
    AI_PREFERENCE_DATA = "ai.preference_data"
    AI_RL_ENVIRONMENT = "ai.rl_environment"
    AI_EMBED = "ai.embed"
    AI_INDEX_RETRIEVAL = "ai.index_retrieval"
    AI_RETRIEVE = "ai.retrieve"
    AI_INFERENCE_INPUT = "ai.inference_input"
    AI_EVALUATE = "ai.evaluate"
    AI_SYNTHESIZE = "ai.synthesize"
    AI_DISTILL = "ai.distill"
    AI_UNLEARN = "ai.unlearn"
    COMMERCIAL_ADVERTISE = "commercial.advertise"
    COMMERCIAL_MEASURE = "commercial.measure"
    COMMERCIAL_PRICE = "commercial.price"
    COMMERCIAL_UNDERWRITE = "commercial.underwrite"
    COMMERCIAL_MARKET_RESEARCH = "commercial.market_research"
    COMMERCIAL_PRODUCT_IMPROVE = "commercial.product_improve"
    COMMERCIAL_FRAUD_DETECT = "commercial.fraud_detect"
    COMMERCIAL_RESELL = "commercial.resell"
    LIFECYCLE_RETAIN = "lifecycle.retain"
    LIFECYCLE_DELETE = "lifecycle.delete"
    LIFECYCLE_RESTRICT = "lifecycle.restrict"
    LIFECYCLE_PORT = "lifecycle.port"

class Purpose(str, Enum):
    """Purposes."""

    SERVICE = "service"
    SERVICE_CORE = "service.core"
    SERVICE_ACCOUNT = "service.account"
    SERVICE_SUPPORT = "service.support"
    SERVICE_PERSONALIZATION = "service.personalization"
    SECURITY = "security"
    SECURITY_FRAUD = "security.fraud"
    SECURITY_ABUSE = "security.abuse"
    SECURITY_AUTHENTICATION = "security.authentication"
    LEGAL = "legal"
    LEGAL_OBLIGATION = "legal.obligation"
    LEGAL_CLAIMS = "legal.claims"
    LEGAL_AUDIT = "legal.audit"
    OPERATIONS = "operations"
    OPERATIONS_RELIABILITY = "operations.reliability"
    OPERATIONS_CAPACITY = "operations.capacity"
    IMPROVEMENT = "improvement"
    IMPROVEMENT_ANALYTICS = "improvement.analytics"
    IMPROVEMENT_EXPERIMENTATION = "improvement.experimentation"
    IMPROVEMENT_AI_TRAINING = "improvement.ai_training"
    IMPROVEMENT_AI_EVALUATION = "improvement.ai_evaluation"
    MARKETING = "marketing"
    MARKETING_DIRECT = "marketing.direct"
    MARKETING_ADVERTISING = "marketing.advertising"
    MARKETING_ADVERTISING_CONTEXTUAL = "marketing.advertising.contextual"
    MARKETING_ADVERTISING_BEHAVIORAL = "marketing.advertising.behavioral"
    MARKETING_MEASUREMENT = "marketing.measurement"
    COMMERCE = "commerce"
    COMMERCE_SALE = "commerce.sale"
    COMMERCE_LICENSING = "commerce.licensing"
    COMMERCE_BROKERAGE = "commerce.brokerage"
    RISK = "risk"
    RISK_CREDIT = "risk.credit"
    RISK_INSURANCE = "risk.insurance"
    RISK_PRICING = "risk.pricing"
    RESEARCH = "research"
    RESEARCH_SCIENTIFIC = "research.scientific"
    RESEARCH_PUBLIC_INTEREST = "research.public_interest"
    RESEARCH_COMMERCIAL = "research.commercial"

class Regime(str, Enum):
    """Regulatory regime tags."""

    EU_GDPR = "eu.gdpr"
    EU_DATA_ACT = "eu.data_act"
    EU_AI_ACT = "eu.ai_act"
    UK_UK_GDPR = "uk.uk_gdpr"
    US_CA_CCPA = "us.ca.ccpa"
    US_CO_CPA = "us.co.cpa"
    US_VA_VCDPA = "us.va.vcdpa"
    US_HIPAA = "us.hipaa"
    US_GLBA = "us.glba"
    US_FCRA = "us.fcra"
    US_COPPA = "us.coppa"
    US_FERPA = "us.ferpa"
    US_IL_BIPA = "us.il.bipa"
    BR_LGPD = "br.lgpd"
    CA_PIPEDA = "ca.pipeda"
    JP_APPI = "jp.appi"
    KR_PIPA = "kr.pipa"
    IN_DPDP = "in.dpdp"
    CN_PIPL = "cn.pipl"
    AU_PRIVACY_ACT = "au.privacy_act"
    ZA_POPIA = "za.popia"

class LawfulBasis(str, Enum):
    """Lawful-basis assertions."""

    CONSENT = "consent"
    CONTRACT = "contract"
    LEGAL_OBLIGATION = "legal_obligation"
    VITAL_INTERESTS = "vital_interests"
    PUBLIC_TASK = "public_task"
    LEGITIMATE_INTERESTS = "legitimate_interests"
    OPT_OUT_RESPECTED = "opt_out_respected"
    PROTOCOL_AUTHORIZATION = "protocol_authorization"

TIER_RANK = {
    SensitivityTier.T0: 0,
    SensitivityTier.T1: 1,
    SensitivityTier.T2: 2,
    SensitivityTier.T3: 3,
    SensitivityTier.T4: 4,
}

DATA_CLASS_SENSITIVITY = {
    DataClass.IDENTITY_DIRECT: SensitivityTier.T3,
    DataClass.IDENTITY_PSEUDONYMOUS: SensitivityTier.T2,
    DataClass.IDENTITY_GOVERNMENT: SensitivityTier.T4,
    DataClass.CONTACT_EMAIL: SensitivityTier.T2,
    DataClass.CONTACT_PHONE: SensitivityTier.T2,
    DataClass.CONTACT_POSTAL: SensitivityTier.T3,
    DataClass.LOCATION_PRECISE: SensitivityTier.T4,
    DataClass.LOCATION_COARSE: SensitivityTier.T2,
    DataClass.LOCATION_INFERRED_HOME: SensitivityTier.T4,
    DataClass.LOCATION_INFERRED_WORK: SensitivityTier.T3,
    DataClass.LOCATION_TRAJECTORY: SensitivityTier.T4,
    DataClass.DEVICE_IDENTIFIER: SensitivityTier.T2,
    DataClass.DEVICE_FINGERPRINT: SensitivityTier.T3,
    DataClass.DEVICE_CONFIGURATION: SensitivityTier.T1,
    DataClass.DEVICE_NETWORK: SensitivityTier.T2,
    DataClass.BEHAVIOR_WEB_BROWSING: SensitivityTier.T2,
    DataClass.BEHAVIOR_APP_USAGE: SensitivityTier.T2,
    DataClass.BEHAVIOR_SEARCH: SensitivityTier.T3,
    DataClass.BEHAVIOR_CONTENT_CONSUMPTION: SensitivityTier.T2,
    DataClass.BEHAVIOR_SOCIAL_GRAPH: SensitivityTier.T3,
    DataClass.BEHAVIOR_KEYSTROKE_DYNAMICS: SensitivityTier.T3,
    DataClass.BEHAVIOR_ATTENTION: SensitivityTier.T3,
    DataClass.TRANSACTION_PURCHASE: SensitivityTier.T2,
    DataClass.TRANSACTION_PAYMENT_INSTRUMENT: SensitivityTier.T4,
    DataClass.FINANCIAL_ACCOUNT: SensitivityTier.T4,
    DataClass.FINANCIAL_CREDITWORTHINESS: SensitivityTier.T4,
    DataClass.FINANCIAL_INCOME: SensitivityTier.T3,
    DataClass.CONTENT_USER_GENERATED: SensitivityTier.T3,
    DataClass.CONTENT_COMMUNICATIONS: SensitivityTier.T4,
    DataClass.CONTENT_MEDIA: SensitivityTier.T3,
    DataClass.BIOMETRIC_TEMPLATE: SensitivityTier.T4,
    DataClass.BIOMETRIC_DERIVED: SensitivityTier.T4,
    DataClass.HEALTH_CLINICAL: SensitivityTier.T4,
    DataClass.HEALTH_WEARABLE: SensitivityTier.T3,
    DataClass.HEALTH_INFERRED: SensitivityTier.T4,
    DataClass.PROTECTED_RACE_ETHNICITY: SensitivityTier.T4,
    DataClass.PROTECTED_RELIGION: SensitivityTier.T4,
    DataClass.PROTECTED_POLITICAL: SensitivityTier.T4,
    DataClass.PROTECTED_SEXUAL_ORIENTATION: SensitivityTier.T4,
    DataClass.PROTECTED_GENETIC: SensitivityTier.T4,
    DataClass.PROTECTED_IMMIGRATION: SensitivityTier.T4,
    DataClass.MINOR_ANY: SensitivityTier.T4,
    DataClass.EDUCATION_RECORD: SensitivityTier.T3,
    DataClass.EMPLOYMENT_RECORD: SensitivityTier.T3,
    DataClass.TELEMETRY_ENTERPRISE: SensitivityTier.T1,
    DataClass.TELEMETRY_SECURITY: SensitivityTier.T2,
    DataClass.TELEMETRY_VEHICLE: SensitivityTier.T3,
    DataClass.TELEMETRY_IOT_HOME: SensitivityTier.T3,
    DataClass.TELEMETRY_IOT_INDUSTRIAL: SensitivityTier.T0,
    DataClass.SENSOR_ENVIRONMENTAL: SensitivityTier.T0,
    DataClass.SENSOR_IMAGING_PUBLIC: SensitivityTier.T3,
    DataClass.INDUSTRIAL_PROCESS: SensitivityTier.T0,
    DataClass.SCIENTIFIC_MEASUREMENT: SensitivityTier.T0,
    DataClass.SCIENTIFIC_HUMAN_SUBJECT: SensitivityTier.T4,
    DataClass.DERIVED_PROFILE: SensitivityTier.T3,
    DataClass.DERIVED_SEGMENT: SensitivityTier.T2,
    DataClass.DERIVED_EMBEDDING: SensitivityTier.T3,
    DataClass.DERIVED_AGGREGATE: SensitivityTier.T1,
    DataClass.DERIVED_DP_AGGREGATE: SensitivityTier.T0,
    DataClass.DERIVED_SYNTHETIC: SensitivityTier.T1,
    DataClass.DERIVED_MODEL_PARAMETERS: SensitivityTier.T2,
}

DATA_CLASS_REID_RISK = {
    DataClass.IDENTITY_DIRECT: 95,
    DataClass.IDENTITY_PSEUDONYMOUS: 60,
    DataClass.IDENTITY_GOVERNMENT: 98,
    DataClass.CONTACT_EMAIL: 85,
    DataClass.CONTACT_PHONE: 88,
    DataClass.CONTACT_POSTAL: 80,
    DataClass.LOCATION_PRECISE: 92,
    DataClass.LOCATION_COARSE: 45,
    DataClass.LOCATION_INFERRED_HOME: 90,
    DataClass.LOCATION_INFERRED_WORK: 78,
    DataClass.LOCATION_TRAJECTORY: 96,
    DataClass.DEVICE_IDENTIFIER: 70,
    DataClass.DEVICE_FINGERPRINT: 82,
    DataClass.DEVICE_CONFIGURATION: 35,
    DataClass.DEVICE_NETWORK: 66,
    DataClass.BEHAVIOR_WEB_BROWSING: 72,
    DataClass.BEHAVIOR_APP_USAGE: 64,
    DataClass.BEHAVIOR_SEARCH: 80,
    DataClass.BEHAVIOR_CONTENT_CONSUMPTION: 58,
    DataClass.BEHAVIOR_SOCIAL_GRAPH: 86,
    DataClass.BEHAVIOR_KEYSTROKE_DYNAMICS: 84,
    DataClass.BEHAVIOR_ATTENTION: 70,
    DataClass.TRANSACTION_PURCHASE: 68,
    DataClass.TRANSACTION_PAYMENT_INSTRUMENT: 90,
    DataClass.FINANCIAL_ACCOUNT: 88,
    DataClass.FINANCIAL_CREDITWORTHINESS: 85,
    DataClass.FINANCIAL_INCOME: 75,
    DataClass.CONTENT_USER_GENERATED: 76,
    DataClass.CONTENT_COMMUNICATIONS: 90,
    DataClass.CONTENT_MEDIA: 82,
    DataClass.BIOMETRIC_TEMPLATE: 99,
    DataClass.BIOMETRIC_DERIVED: 88,
    DataClass.HEALTH_CLINICAL: 94,
    DataClass.HEALTH_WEARABLE: 80,
    DataClass.HEALTH_INFERRED: 86,
    DataClass.PROTECTED_RACE_ETHNICITY: 70,
    DataClass.PROTECTED_RELIGION: 70,
    DataClass.PROTECTED_POLITICAL: 72,
    DataClass.PROTECTED_SEXUAL_ORIENTATION: 74,
    DataClass.PROTECTED_GENETIC: 99,
    DataClass.PROTECTED_IMMIGRATION: 76,
    DataClass.MINOR_ANY: 80,
    DataClass.EDUCATION_RECORD: 78,
    DataClass.EMPLOYMENT_RECORD: 80,
    DataClass.TELEMETRY_ENTERPRISE: 25,
    DataClass.TELEMETRY_SECURITY: 55,
    DataClass.TELEMETRY_VEHICLE: 80,
    DataClass.TELEMETRY_IOT_HOME: 74,
    DataClass.TELEMETRY_IOT_INDUSTRIAL: 5,
    DataClass.SENSOR_ENVIRONMENTAL: 3,
    DataClass.SENSOR_IMAGING_PUBLIC: 70,
    DataClass.INDUSTRIAL_PROCESS: 4,
    DataClass.SCIENTIFIC_MEASUREMENT: 4,
    DataClass.SCIENTIFIC_HUMAN_SUBJECT: 88,
    DataClass.DERIVED_PROFILE: 84,
    DataClass.DERIVED_SEGMENT: 50,
    DataClass.DERIVED_EMBEDDING: 65,
    DataClass.DERIVED_AGGREGATE: 12,
    DataClass.DERIVED_DP_AGGREGATE: 2,
    DataClass.DERIVED_SYNTHETIC: 20,
    DataClass.DERIVED_MODEL_PARAMETERS: 40,
}

DATA_CLASS_SPECIAL = {
    DataClass.IDENTITY_DIRECT: [],
    DataClass.IDENTITY_PSEUDONYMOUS: [],
    DataClass.IDENTITY_GOVERNMENT: ['us.ssn'],
    DataClass.CONTACT_EMAIL: [],
    DataClass.CONTACT_PHONE: [],
    DataClass.CONTACT_POSTAL: [],
    DataClass.LOCATION_PRECISE: ['ccpa.precise_geolocation'],
    DataClass.LOCATION_COARSE: [],
    DataClass.LOCATION_INFERRED_HOME: [],
    DataClass.LOCATION_INFERRED_WORK: [],
    DataClass.LOCATION_TRAJECTORY: ['ccpa.precise_geolocation'],
    DataClass.DEVICE_IDENTIFIER: [],
    DataClass.DEVICE_FINGERPRINT: [],
    DataClass.DEVICE_CONFIGURATION: [],
    DataClass.DEVICE_NETWORK: [],
    DataClass.BEHAVIOR_WEB_BROWSING: [],
    DataClass.BEHAVIOR_APP_USAGE: [],
    DataClass.BEHAVIOR_SEARCH: [],
    DataClass.BEHAVIOR_CONTENT_CONSUMPTION: [],
    DataClass.BEHAVIOR_SOCIAL_GRAPH: [],
    DataClass.BEHAVIOR_KEYSTROKE_DYNAMICS: [],
    DataClass.BEHAVIOR_ATTENTION: [],
    DataClass.TRANSACTION_PURCHASE: [],
    DataClass.TRANSACTION_PAYMENT_INSTRUMENT: ['pci.chd'],
    DataClass.FINANCIAL_ACCOUNT: ['us.glba.npi'],
    DataClass.FINANCIAL_CREDITWORTHINESS: ['us.fcra'],
    DataClass.FINANCIAL_INCOME: [],
    DataClass.CONTENT_USER_GENERATED: [],
    DataClass.CONTENT_COMMUNICATIONS: ['us.ecpa'],
    DataClass.CONTENT_MEDIA: [],
    DataClass.BIOMETRIC_TEMPLATE: ['gdpr.art9', 'us.il.bipa', 'ccpa.biometric'],
    DataClass.BIOMETRIC_DERIVED: ['gdpr.art9', 'ccpa.biometric'],
    DataClass.HEALTH_CLINICAL: ['gdpr.art9', 'us.hipaa.phi'],
    DataClass.HEALTH_WEARABLE: ['gdpr.art9'],
    DataClass.HEALTH_INFERRED: ['gdpr.art9'],
    DataClass.PROTECTED_RACE_ETHNICITY: ['gdpr.art9', 'ccpa.sensitive'],
    DataClass.PROTECTED_RELIGION: ['gdpr.art9', 'ccpa.sensitive'],
    DataClass.PROTECTED_POLITICAL: ['gdpr.art9', 'ccpa.sensitive'],
    DataClass.PROTECTED_SEXUAL_ORIENTATION: ['gdpr.art9', 'ccpa.sensitive'],
    DataClass.PROTECTED_GENETIC: ['gdpr.art9', 'us.gina'],
    DataClass.PROTECTED_IMMIGRATION: ['gdpr.art9'],
    DataClass.MINOR_ANY: ['us.coppa', 'gdpr.art8'],
    DataClass.EDUCATION_RECORD: ['us.ferpa'],
    DataClass.EMPLOYMENT_RECORD: [],
    DataClass.TELEMETRY_ENTERPRISE: [],
    DataClass.TELEMETRY_SECURITY: [],
    DataClass.TELEMETRY_VEHICLE: [],
    DataClass.TELEMETRY_IOT_HOME: [],
    DataClass.TELEMETRY_IOT_INDUSTRIAL: [],
    DataClass.SENSOR_ENVIRONMENTAL: [],
    DataClass.SENSOR_IMAGING_PUBLIC: [],
    DataClass.INDUSTRIAL_PROCESS: [],
    DataClass.SCIENTIFIC_MEASUREMENT: [],
    DataClass.SCIENTIFIC_HUMAN_SUBJECT: ['us.common_rule', 'gdpr.art9'],
    DataClass.DERIVED_PROFILE: [],
    DataClass.DERIVED_SEGMENT: [],
    DataClass.DERIVED_EMBEDDING: [],
    DataClass.DERIVED_AGGREGATE: [],
    DataClass.DERIVED_DP_AGGREGATE: [],
    DataClass.DERIVED_SYNTHETIC: [],
    DataClass.DERIVED_MODEL_PARAMETERS: [],
}

OPERATION_METER = {
    Operation.COLLECT_OBSERVE: Unit.RECORD,
    Operation.COLLECT_RECEIVE: Unit.RECORD,
    Operation.COLLECT_GENERATE: Unit.RECORD,
    Operation.STORE_PERSIST: Unit.SUBJECT_DAY,
    Operation.STORE_REPLICATE: Unit.SUBJECT_DAY,
    Operation.STORE_BACKUP: Unit.SUBJECT_DAY,
    Operation.ACCESS_READ: Unit.RECORD,
    Operation.ACCESS_QUERY: Unit.QUERY,
    Operation.ACCESS_INDEX: Unit.RECORD,
    Operation.ACCESS_EXPORT_VIEW: Unit.RECORD,
    Operation.PROCESS_TRANSFORM: Unit.RECORD,
    Operation.PROCESS_AGGREGATE: Unit.RECORD,
    Operation.PROCESS_CLASSIFY: Unit.INFERENCE,
    Operation.PROCESS_PROFILE: Unit.INFERENCE,
    Operation.PROCESS_SCORE: Unit.INFERENCE,
    Operation.PROCESS_PERSONALIZE: Unit.INFERENCE,
    Operation.PROCESS_RECOMMEND: Unit.INFERENCE,
    Operation.PROCESS_PREDICT: Unit.INFERENCE,
    Operation.PROCESS_MATCH: Unit.RECORD,
    Operation.PROCESS_DEIDENTIFY: Unit.RECORD,
    Operation.PROCESS_ANONYMIZE: Unit.RECORD,
    Operation.PROCESS_DP_RELEASE: Unit.QUERY,
    Operation.TRANSFER_INTERNAL: Unit.RECORD,
    Operation.TRANSFER_AFFILIATE: Unit.RECORD,
    Operation.TRANSFER_PROCESSOR: Unit.RECORD,
    Operation.TRANSFER_CONTROLLER: Unit.RECORD,
    Operation.TRANSFER_SALE: Unit.RECORD,
    Operation.TRANSFER_LICENSE: Unit.RECORD,
    Operation.TRANSFER_API_ACCESS: Unit.QUERY,
    Operation.TRANSFER_EXPORT_JURISDICTION: Unit.RECORD,
    Operation.TRANSFER_PUBLISH: Unit.RECORD,
    Operation.AI_PRETRAIN: Unit.TOKEN,
    Operation.AI_FINETUNE: Unit.TOKEN,
    Operation.AI_INSTRUCTION_TUNE: Unit.TOKEN,
    Operation.AI_PREFERENCE_DATA: Unit.COMPARISON,
    Operation.AI_RL_ENVIRONMENT: Unit.EPISODE,
    Operation.AI_EMBED: Unit.RECORD,
    Operation.AI_INDEX_RETRIEVAL: Unit.RECORD,
    Operation.AI_RETRIEVE: Unit.RETRIEVAL,
    Operation.AI_INFERENCE_INPUT: Unit.INFERENCE,
    Operation.AI_EVALUATE: Unit.RECORD,
    Operation.AI_SYNTHESIZE: Unit.RECORD,
    Operation.AI_DISTILL: Unit.TOKEN,
    Operation.AI_UNLEARN: Unit.RECORD,
    Operation.COMMERCIAL_ADVERTISE: Unit.IMPRESSION,
    Operation.COMMERCIAL_MEASURE: Unit.IMPRESSION,
    Operation.COMMERCIAL_PRICE: Unit.INFERENCE,
    Operation.COMMERCIAL_UNDERWRITE: Unit.INFERENCE,
    Operation.COMMERCIAL_MARKET_RESEARCH: Unit.RECORD,
    Operation.COMMERCIAL_PRODUCT_IMPROVE: Unit.RECORD,
    Operation.COMMERCIAL_FRAUD_DETECT: Unit.INFERENCE,
    Operation.COMMERCIAL_RESELL: Unit.RECORD,
    Operation.LIFECYCLE_RETAIN: Unit.SUBJECT_DAY,
    Operation.LIFECYCLE_DELETE: Unit.RECORD,
    Operation.LIFECYCLE_RESTRICT: Unit.RECORD,
    Operation.LIFECYCLE_PORT: Unit.RECORD,
}

OPERATION_DERIVES = {
    Operation.COLLECT_OBSERVE: False,
    Operation.COLLECT_RECEIVE: False,
    Operation.COLLECT_GENERATE: True,
    Operation.STORE_PERSIST: False,
    Operation.STORE_REPLICATE: False,
    Operation.STORE_BACKUP: False,
    Operation.ACCESS_READ: False,
    Operation.ACCESS_QUERY: False,
    Operation.ACCESS_INDEX: True,
    Operation.ACCESS_EXPORT_VIEW: True,
    Operation.PROCESS_TRANSFORM: True,
    Operation.PROCESS_AGGREGATE: True,
    Operation.PROCESS_CLASSIFY: True,
    Operation.PROCESS_PROFILE: True,
    Operation.PROCESS_SCORE: True,
    Operation.PROCESS_PERSONALIZE: False,
    Operation.PROCESS_RECOMMEND: False,
    Operation.PROCESS_PREDICT: True,
    Operation.PROCESS_MATCH: True,
    Operation.PROCESS_DEIDENTIFY: True,
    Operation.PROCESS_ANONYMIZE: True,
    Operation.PROCESS_DP_RELEASE: True,
    Operation.TRANSFER_INTERNAL: False,
    Operation.TRANSFER_AFFILIATE: False,
    Operation.TRANSFER_PROCESSOR: False,
    Operation.TRANSFER_CONTROLLER: False,
    Operation.TRANSFER_SALE: False,
    Operation.TRANSFER_LICENSE: False,
    Operation.TRANSFER_API_ACCESS: False,
    Operation.TRANSFER_EXPORT_JURISDICTION: False,
    Operation.TRANSFER_PUBLISH: False,
    Operation.AI_PRETRAIN: True,
    Operation.AI_FINETUNE: True,
    Operation.AI_INSTRUCTION_TUNE: True,
    Operation.AI_PREFERENCE_DATA: True,
    Operation.AI_RL_ENVIRONMENT: True,
    Operation.AI_EMBED: True,
    Operation.AI_INDEX_RETRIEVAL: True,
    Operation.AI_RETRIEVE: False,
    Operation.AI_INFERENCE_INPUT: False,
    Operation.AI_EVALUATE: True,
    Operation.AI_SYNTHESIZE: True,
    Operation.AI_DISTILL: True,
    Operation.AI_UNLEARN: True,
    Operation.COMMERCIAL_ADVERTISE: False,
    Operation.COMMERCIAL_MEASURE: False,
    Operation.COMMERCIAL_PRICE: False,
    Operation.COMMERCIAL_UNDERWRITE: False,
    Operation.COMMERCIAL_MARKET_RESEARCH: False,
    Operation.COMMERCIAL_PRODUCT_IMPROVE: False,
    Operation.COMMERCIAL_FRAUD_DETECT: False,
    Operation.COMMERCIAL_RESELL: False,
    Operation.LIFECYCLE_RETAIN: False,
    Operation.LIFECYCLE_DELETE: False,
    Operation.LIFECYCLE_RESTRICT: False,
    Operation.LIFECYCLE_PORT: False,
}

OPERATION_FAMILY = {
    Operation.COLLECT_OBSERVE: "collect",
    Operation.COLLECT_RECEIVE: "collect",
    Operation.COLLECT_GENERATE: "collect",
    Operation.STORE_PERSIST: "process",
    Operation.STORE_REPLICATE: "process",
    Operation.STORE_BACKUP: "process",
    Operation.ACCESS_READ: "process",
    Operation.ACCESS_QUERY: "process",
    Operation.ACCESS_INDEX: "process",
    Operation.ACCESS_EXPORT_VIEW: "process",
    Operation.PROCESS_TRANSFORM: "process",
    Operation.PROCESS_AGGREGATE: "process",
    Operation.PROCESS_CLASSIFY: "process",
    Operation.PROCESS_PROFILE: "process",
    Operation.PROCESS_SCORE: "process",
    Operation.PROCESS_PERSONALIZE: "process",
    Operation.PROCESS_RECOMMEND: "process",
    Operation.PROCESS_PREDICT: "process",
    Operation.PROCESS_MATCH: "process",
    Operation.PROCESS_DEIDENTIFY: "process",
    Operation.PROCESS_ANONYMIZE: "process",
    Operation.PROCESS_DP_RELEASE: "process",
    Operation.TRANSFER_INTERNAL: "transfer",
    Operation.TRANSFER_AFFILIATE: "transfer",
    Operation.TRANSFER_PROCESSOR: "transfer",
    Operation.TRANSFER_CONTROLLER: "transfer",
    Operation.TRANSFER_SALE: "transfer",
    Operation.TRANSFER_LICENSE: "transfer",
    Operation.TRANSFER_API_ACCESS: "transfer",
    Operation.TRANSFER_EXPORT_JURISDICTION: "transfer",
    Operation.TRANSFER_PUBLISH: "transfer",
    Operation.AI_PRETRAIN: "ai",
    Operation.AI_FINETUNE: "ai",
    Operation.AI_INSTRUCTION_TUNE: "ai",
    Operation.AI_PREFERENCE_DATA: "ai",
    Operation.AI_RL_ENVIRONMENT: "ai",
    Operation.AI_EMBED: "ai",
    Operation.AI_INDEX_RETRIEVAL: "ai",
    Operation.AI_RETRIEVE: "ai",
    Operation.AI_INFERENCE_INPUT: "ai",
    Operation.AI_EVALUATE: "ai",
    Operation.AI_SYNTHESIZE: "ai",
    Operation.AI_DISTILL: "ai",
    Operation.AI_UNLEARN: "ai",
    Operation.COMMERCIAL_ADVERTISE: "commercialize",
    Operation.COMMERCIAL_MEASURE: "commercialize",
    Operation.COMMERCIAL_PRICE: "commercialize",
    Operation.COMMERCIAL_UNDERWRITE: "commercialize",
    Operation.COMMERCIAL_MARKET_RESEARCH: "commercialize",
    Operation.COMMERCIAL_PRODUCT_IMPROVE: "commercialize",
    Operation.COMMERCIAL_FRAUD_DETECT: "commercialize",
    Operation.COMMERCIAL_RESELL: "commercialize",
    Operation.LIFECYCLE_RETAIN: "lifecycle",
    Operation.LIFECYCLE_DELETE: "lifecycle",
    Operation.LIFECYCLE_RESTRICT: "lifecycle",
    Operation.LIFECYCLE_PORT: "lifecycle",
}

UNIT_ADDITIVE = {
    Unit.RECORD: True,
    Unit.BYTE: True,
    Unit.SUBJECT_DAY: True,
    Unit.QUERY: True,
    Unit.INFERENCE: True,
    Unit.IMPRESSION: True,
    Unit.TOKEN: True,
    Unit.COMPARISON: True,
    Unit.EPISODE: True,
    Unit.RETRIEVAL: True,
    Unit.GRADIENT_STEP: True,
    Unit.SHARE: False,
}

PURPOSE_PARENT: dict[Purpose, Optional[Purpose]] = {
    Purpose.SERVICE: None,
    Purpose.SERVICE_CORE: Purpose.SERVICE,
    Purpose.SERVICE_ACCOUNT: Purpose.SERVICE,
    Purpose.SERVICE_SUPPORT: Purpose.SERVICE,
    Purpose.SERVICE_PERSONALIZATION: Purpose.SERVICE,
    Purpose.SECURITY: None,
    Purpose.SECURITY_FRAUD: Purpose.SECURITY,
    Purpose.SECURITY_ABUSE: Purpose.SECURITY,
    Purpose.SECURITY_AUTHENTICATION: Purpose.SECURITY,
    Purpose.LEGAL: None,
    Purpose.LEGAL_OBLIGATION: Purpose.LEGAL,
    Purpose.LEGAL_CLAIMS: Purpose.LEGAL,
    Purpose.LEGAL_AUDIT: Purpose.LEGAL,
    Purpose.OPERATIONS: None,
    Purpose.OPERATIONS_RELIABILITY: Purpose.OPERATIONS,
    Purpose.OPERATIONS_CAPACITY: Purpose.OPERATIONS,
    Purpose.IMPROVEMENT: None,
    Purpose.IMPROVEMENT_ANALYTICS: Purpose.IMPROVEMENT,
    Purpose.IMPROVEMENT_EXPERIMENTATION: Purpose.IMPROVEMENT,
    Purpose.IMPROVEMENT_AI_TRAINING: Purpose.IMPROVEMENT,
    Purpose.IMPROVEMENT_AI_EVALUATION: Purpose.IMPROVEMENT,
    Purpose.MARKETING: None,
    Purpose.MARKETING_DIRECT: Purpose.MARKETING,
    Purpose.MARKETING_ADVERTISING: Purpose.MARKETING,
    Purpose.MARKETING_ADVERTISING_CONTEXTUAL: Purpose.MARKETING_ADVERTISING,
    Purpose.MARKETING_ADVERTISING_BEHAVIORAL: Purpose.MARKETING_ADVERTISING,
    Purpose.MARKETING_MEASUREMENT: Purpose.MARKETING,
    Purpose.COMMERCE: None,
    Purpose.COMMERCE_SALE: Purpose.COMMERCE,
    Purpose.COMMERCE_LICENSING: Purpose.COMMERCE,
    Purpose.COMMERCE_BROKERAGE: Purpose.COMMERCE,
    Purpose.RISK: None,
    Purpose.RISK_CREDIT: Purpose.RISK,
    Purpose.RISK_INSURANCE: Purpose.RISK,
    Purpose.RISK_PRICING: Purpose.RISK,
    Purpose.RESEARCH: None,
    Purpose.RESEARCH_SCIENTIFIC: Purpose.RESEARCH,
    Purpose.RESEARCH_PUBLIC_INTEREST: Purpose.RESEARCH,
    Purpose.RESEARCH_COMMERCIAL: Purpose.RESEARCH,
}

PURPOSE_COMMERCIAL = {
    Purpose.SERVICE: False,
    Purpose.SERVICE_CORE: False,
    Purpose.SERVICE_ACCOUNT: False,
    Purpose.SERVICE_SUPPORT: False,
    Purpose.SERVICE_PERSONALIZATION: False,
    Purpose.SECURITY: False,
    Purpose.SECURITY_FRAUD: False,
    Purpose.SECURITY_ABUSE: False,
    Purpose.SECURITY_AUTHENTICATION: False,
    Purpose.LEGAL: False,
    Purpose.LEGAL_OBLIGATION: False,
    Purpose.LEGAL_CLAIMS: False,
    Purpose.LEGAL_AUDIT: False,
    Purpose.OPERATIONS: False,
    Purpose.OPERATIONS_RELIABILITY: False,
    Purpose.OPERATIONS_CAPACITY: False,
    Purpose.IMPROVEMENT: True,
    Purpose.IMPROVEMENT_ANALYTICS: True,
    Purpose.IMPROVEMENT_EXPERIMENTATION: True,
    Purpose.IMPROVEMENT_AI_TRAINING: True,
    Purpose.IMPROVEMENT_AI_EVALUATION: True,
    Purpose.MARKETING: True,
    Purpose.MARKETING_DIRECT: True,
    Purpose.MARKETING_ADVERTISING: True,
    Purpose.MARKETING_ADVERTISING_CONTEXTUAL: True,
    Purpose.MARKETING_ADVERTISING_BEHAVIORAL: True,
    Purpose.MARKETING_MEASUREMENT: True,
    Purpose.COMMERCE: True,
    Purpose.COMMERCE_SALE: True,
    Purpose.COMMERCE_LICENSING: True,
    Purpose.COMMERCE_BROKERAGE: True,
    Purpose.RISK: True,
    Purpose.RISK_CREDIT: True,
    Purpose.RISK_INSURANCE: True,
    Purpose.RISK_PRICING: True,
    Purpose.RESEARCH: False,
    Purpose.RESEARCH_SCIENTIFIC: False,
    Purpose.RESEARCH_PUBLIC_INTEREST: False,
    Purpose.RESEARCH_COMMERCIAL: True,
}



def purpose_covers(broad: Purpose, narrow: Purpose) -> bool:
    """True if `broad` is `narrow` or an ancestor of it in the purpose lattice."""
    cur: Optional[Purpose] = narrow
    while cur is not None:
        if cur == broad:
            return True
        cur = PURPOSE_PARENT[cur]
    return False
